{% set name = "wield.pytest" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wield.pytest-{{ version }}.tar.gz
  sha256: 7669bd0b54920a898ef0efea7e8c5ac60d5ff67aa148c3bdb1cc8939655224d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pytest

test:
  imports:
    - wield.pytest
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wieldphysics/wield-pytest
  summary: pytest fixtures and extension for notebook via test
  license: Apache-2.0
  license_file: LICENSES/

extra:
  recipe-maintainers:
    - mccullerlp 
